language: python
before_install:
    - pip install pytest
script:
    - python -m pytest -v

matrix:
    include:
        - sudo: False
          dist: trusty
          python: 2.7
        - sudo: False
          dist: trusty
          python: 3.4
        - sudo: False
          dist: trusty
          python: 3.5
        - sudo: False
          dist: trusty
          python: 3.6
        - sudo: required
          dist: xenial
          python: 3.7-dev
        - sudo: False
          dist: trusty
          python: pypy
        - sudo: False
          dist: trusty
          python: pypy3
