language: python
before_install:
    # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-382599654
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo sudo apt-get update; fi
install:
    - pip install -r developer_requirements.txt
script:
    - ./run-tests.sh
    - codecov
    - docker run --rm -v "$(pwd):/data" quay.io/pypa/manylinux1_x86_64 bash -c "/data/.travis_build_wheel.sh $TRAVIS_PYTHON_VERSION"
deploy:
    provider: releases
    api_key:
        secure: "DqDkKBKw20riyr1WeRZtMEUlmD9cCJNf/JJD5res8HSx8wUz+rI1aDpk0wCaehdLS2zsvUpf027EHfkseUZaMr3wMfwHQ9FxSEOZ04K8Wmxqk60bzEHwqL6xBe7M3K3RxYUKH6oZDekN2I0imkllHA4v6iG0JGmoacNAos60NdA="
    file_glob: true
    file: 'dist/fastavro-*.whl'
    skip_cleanup: true
    on:
        tags: true
        condition: $TRAVIS_PYTHON_VERSION != *"pypy"*

matrix:
    include:
        - sudo: False
          dist: trusty
          python: 2.7
        - sudo: False
          dist: trusty
          python: 3.4
        - sudo: False
          dist: trusty
          python: 3.5
        - sudo: False
          dist: trusty
          python: 3.6
        - sudo: required
          dist: xenial
          python: 3.7-dev
        - sudo: False
          dist: trusty
          python: pypy
        - sudo: False
          dist: trusty
          python: pypy3
